In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from tqdm import tqdm

C:\Users\duasp\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [2]:
# Some Basic Directories for housekeeping
# set location of input files:
inpDir = os.path.join( '..', 'input')

outDir = os.path.join('..', 'output')

# define and set random state 
RANDOM_STATE = 24
np.random.seed(RANDOM_STATE) # Set Random Seed for reproducible results
SMALL_ENOUGH = 1e-3
GAMMA = 1.0    # 0.99
ALL_POSSIBLE_ACTIONS = ('U', 'D', 'L', 'R')

CMAP = plt.cm.rainbow
plt.set_cmap(CMAP);
plt.style.use('seaborn-v0_8-darkgrid') # plt.style.use('ggplot')

# Define constants for data manipulation
TEST_SIZE = 0.2
NOISE = 0.2
N_SAMPLE = 1024

<Figure size 640x480 with 0 Axes>

In [3]:
# parameters for Matplotlib
params = {'legend.fontsize': 'x-large',    
          'figure.figsize': (15, 8),
          'axes.labelsize': 'x-large',
          'axes.titlesize':'x-large',
          'xtick.labelsize':'x-large',
          'ytick.labelsize':'x-large',
          'savefig.dpi': 75,
          'image.cmap': 'summer',
          'image.interpolation': 'none',
          'savefig.bbox' : 'tight',
          'lines.linewidth' : 1,
          'legend.numpoints' : 1
         }


plt.rcParams.update(params)

'''plt.rc('axes', prop_cycle=(
    cycler('color', mglearn.plot_helpers.cm_cycle.colors) +
    cycler('linestyle', ['-', '-', "--", (0, (3, 3)), (0, (1.5, 1.5))])))
'''
np.set_printoptions(precision=3, suppress=True)

pd.set_option("display.max_columns", 8)
pd.set_option('display.precision', 2)

__all__ = ['np', 'display', 'plt', 'pd', 'sklearn', 'seaborn']

* wt = [1,5,6,8,9]
* val = [10,8,6,4,2]
* W = 11kg

In [4]:
wt = [1,5,6,8,9]
val = [10,8,6,4,2]
W = 11

In [5]:
def solve_rec(wt, val, W, n):
    '''
        Args:
            wt: list of weights in the room
            val: respective values
            W: capacity of the knapsack
            n: number of items
    '''
    
    # Base condition
    if n == 0:
        return 0   # nothing to pick
    if W == 0:
        return 0   # nosapre capacity in the bag
    
    # Decision Tree
    if W < wt[n - 1]:
        return solve_rec(wt, val, W, n-1)      # do not keep, call the fn again with one less items
    else:
        return max(val[n - 1] + solve_rec(wt, val, W - wt[n - 1], n - 1),      # keep in knapsack
                   solve_rec(wt, val, W, n - 1))      # ignore current item

In [6]:
solve_rec(wt, val, W, len(wt))

18

### Knapsack with Memoization

In [7]:
def knap_sack_rec(W: int,
                 wt: list,
                 val: list,
                 n: int):
    #print(W, wt[n], val[n],n)
    
    # abse condition
    if W == 0 or n == 0:    # either we do not want to put
        return 0         # any thing in the sack or there are no items
    
    # if value exists, return the value
    if dp[n][W] != -1:
        return dp[n][W]
    
    # Decision Tree
    if W >= wt[n - 1]:       # if next weight is more than the weight of item under consideration
        dp[n][W] = max(val[n - 1] + knap_sack_rec(W-wt[n - 1], wt, val, n - 1),
                     knap_sack_rec(W, wt, val, n - 1))
    else:
        dp[n][W] = knap_sack_rec(W, wt, val, n - 1) 
    return(dp[n][W])
if __name__=='__main__':
              
    n = len(val)      # how many items
              
    dp = np.array([[-1 for _ in range(W + 1)] for _ in range(n + 1)])
    
    print(knap_sack_rec(W, wt, val, n))      # Process DP and fill with values
              
    print(f'Shape of DP Aray: {dp.shape}')
    print('\n',dp)

18
Shape of DP Aray: (6, 12)

 [[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 10 10 -1 10 10 -1 -1 -1 -1 10]
 [-1 -1 10 10 -1 10 -1 -1 -1 -1 -1 18]
 [-1 -1 10 10 -1 -1 -1 -1 -1 -1 -1 18]
 [-1 -1 10 -1 -1 -1 -1 -1 -1 -1 -1 18]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 18]]


In [ ]:
def fibonacci(n):
    if n<=1:
        return n
    
    else:
        return fibonacci(n-1)+fibonacci(n-2)
    
n=100
print("Fibonacci number at index",n,"is:",fibonacci(n))

In [ ]:
### Bottom 